#!/usr/bin/env python3
"""
tools/init_config.py
────────────────────
GUI wizard (tkinter) that guides you through creating an AvisTrack YAML
config file.  Uses native folder / file picker dialogs so you never have
to type a path manually.

Usage
-----
    python tools/init_config.py              # launch GUI
    python tools/init_config.py --cli        # fallback terminal mode
    python tools/init_config.py --root /media/woodlab/104-A/Wave2  # pre-fill root
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


# ══════════════════════════════════════════════════════════════════════════
#  Shared helpers (used by both GUI and CLI modes)
# ══════════════════════════════════════════════════════════════════════════

STANDARD_DIRS = {
    "00_raw_videos":         "raw_videos",
    "00_Raw_Videos":         "raw_videos",
    "01_Dataset_MOT_Format": "dataset",
    "02_Global_Metadata":    "metadata",
    "03_Model_Training":     "model_training",
}


def _detect_structure(root: str) -> dict[str, str]:
    """Scan root for standard folder names → {config_key: abs_path}."""
    found: dict[str, str] = {}
    root_p = Path(root)
    if not root_p.exists():
        return found
    for child in root_p.iterdir():
        if child.is_dir() and child.name in STANDARD_DIRS:
            found[STANDARD_DIRS[child.name]] = str(child)
    return found


def _find_weights(root: str) -> list[str]:
    """Recursively find .pt weight files under root/03_Model_Training."""
    training_dir = Path(root) / "03_Model_Training"
    if not training_dir.exists():
        return []
    return sorted(str(p) for p in training_dir.rglob("*.pt"))


def _find_roi_file(root: str) -> str | None:
    candidate = Path(root) / "02_Global_Metadata" / "camera_rois.json"
    return str(candidate) if candidate.exists() else None


def _generate_yaml(c: dict) -> str:
    """Build a well-commented YAML string from the collected values."""
    root = c["root"]

    def _rel(path: str) -> str:
        if path.startswith(root):
            return "{root}" + path[len(root):]
        return path

    # Build weights line
    if c.get("weights"):
        weights_line = f'"{_rel(c["weights"])}"'
    else:
        weights_line = "null  # not yet trained"

    # Build pipeline lines
    pipeline_lines = "\n".join(f"  - step: {s}" for s in c["pipeline"])

    # Build model extras (realtime mode)
    model_extra_lines = ""
    if c.get("model_mode") == "realtime":
        model_extra_lines = (
            '  keypoint_name: "center"\n'
            "  kalman_filter:\n"
            "    R: 5.0\n"
            "    Q: 0.001\n"
            "    P: 1000.0\n"
        )

    # Assemble YAML line by line (no textwrap.dedent pitfalls)
    lines = [
        "# ──────────────────────────────────────────────────────────────",
        f"#  AvisTrack Config — {c['experiment']}",
        "#  Generated by: tools/init_config.py",
        "# ──────────────────────────────────────────────────────────────",
        "",
        f'experiment: "{c["experiment"]}"',
        "",
        "# ── Drive / NAS paths ──────────────────────────────────────────",
        "# '{root}' = experiment root; resolved automatically at load time.",
        "drive:",
        f'  root:           "{root}"',
        f'  raw_videos:     "{_rel(c["raw_videos"])}"',
        f'  dataset:        "{_rel(c["dataset"])}"',
        f'  metadata:       "{_rel(c["metadata"])}"',
        f'  roi_file:       "{_rel(c["roi_file"])}"',
        f'  exclusions:     "{_rel(c["exclusions"])}"',
        f'  ocr_roi:        "{_rel(c["ocr_roi"])}"',
        f'  time_calibration: "{_rel(c["time_calibration"])}"',
        f'  train_manifest: "{_rel(c["train_manifest"])}"',
        f'  val_manifest:   "{_rel(c["val_manifest"])}"',
        f'  test_manifest:  "{_rel(c["test_manifest"])}"',
        "",
        "# ── Chamber parameters ─────────────────────────────────────────",
        "chamber:",
        f"  n_subjects:  {c['n_subjects']}",
        f"  fps:         {c['fps']}",
        f"  target_size: [{c['target_w']}, {c['target_h']}]",
        "",
        "# ── Model ──────────────────────────────────────────────────────",
        "model:",
        f'  backend: "{c["backend"]}"',
        f'  mode:    "{c["model_mode"]}"',
        f"  weights: {weights_line}",
    ]

    if model_extra_lines:
        lines.append(model_extra_lines.rstrip())

    lines += [
        "",
        "# ── Tracking ───────────────────────────────────────────────────",
        "tracking:",
        f"  conf_threshold: {c['conf_threshold']}",
        f"  max_gap_frames: {c['max_gap_frames']}",
        "",
        "# ── Pipeline ───────────────────────────────────────────────────",
        "pipeline:",
        pipeline_lines,
        "",
        "# ── Output ─────────────────────────────────────────────────────",
        "output:",
        f'  format: "{c["output_format"]}"',
        f'  dir:    "{_rel(c["output_dir"])}"',
        "",
        "# ── Time calibration ───────────────────────────────────────────",
        "# Used by tools/calibrate_time.py to map frame↔burn-in time via OCR.",
        "time:",
        f'  timezone:    "{c.get("timezone", "America/New_York")}"',
        f'  time_format: "{c.get("time_format", "%I:%M:%S %p")}"',
        "",
    ]

    return "\n".join(lines) + "\n"


def _validate_config(c: dict) -> list[str]:
    """Return a list of warning strings (empty = all good)."""
    warnings: list[str] = []
    root = Path(c["root"])
    if not root.exists():
        warnings.append(f"drive.root does not exist: {root}")
    raw = Path(c["raw_videos"].replace("{root}", c["root"]))
    if root.exists() and not raw.exists():
        warnings.append(f"raw_videos dir not found: {raw}")
    if c.get("weights"):
        w_path = c["weights"].replace("{root}", c["root"])
        if root.exists() and not Path(w_path).exists():
            warnings.append(f"weights file not found: {w_path}")
    roi = c["roi_file"].replace("{root}", c["root"])
    if root.exists() and "transform" in c["pipeline"] and not Path(roi).exists():
        warnings.append(f"roi_file not found (needed by transform step): {roi}")
    return warnings


# ══════════════════════════════════════════════════════════════════════════
#  GUI  (tkinter)
# ══════════════════════════════════════════════════════════════════════════

def _run_gui(prefill_root: str | None = None, prefill_name: str | None = None):
    import tkinter as tk
    from tkinter import ttk, filedialog, messagebox

    # ── Colour palette ────────────────────────────────────────────────────
    BG       = "#1e1e2e"
    FG       = "#cdd6f4"
    ACCENT   = "#89b4fa"
    ENTRY_BG = "#313244"
    OK_GREEN = "#a6e3a1"
    WARN_YEL = "#f9e2af"
    BTN_BG   = "#45475a"
    BTN_FG   = "#cdd6f4"

    root_win = tk.Tk()
    root_win.title("AvisTrack — Config Wizard")
    root_win.configure(bg=BG)
    root_win.minsize(780, 720)

    # ── Style ─────────────────────────────────────────────────────────────
    style = ttk.Style(root_win)
    style.theme_use("clam")

    style.configure(".", background=BG, foreground=FG, fieldbackground=ENTRY_BG)
    style.configure("TFrame",      background=BG)
    style.configure("TLabel",      background=BG, foreground=FG, font=("Segoe UI", 10))
    style.configure("TLabelframe",       background=BG, foreground=ACCENT, font=("Segoe UI", 11, "bold"))
    style.configure("TLabelframe.Label", background=BG, foreground=ACCENT)
    style.configure("TEntry",      fieldbackground=ENTRY_BG, foreground=FG, insertcolor=FG)
    style.configure("TCheckbutton", background=BG, foreground=FG)
    style.configure("TCombobox",   fieldbackground=ENTRY_BG, foreground=FG,
                    selectbackground=ACCENT, selectforeground=BG)
    style.map("TCombobox", fieldbackground=[("readonly", ENTRY_BG)])
    style.configure("TButton",    background=BTN_BG, foreground=BTN_FG, font=("Segoe UI", 10))
    style.map("TButton", background=[("active", ACCENT)], foreground=[("active", BG)])
    style.configure("Accent.TButton", background=ACCENT, foreground=BG,
                    font=("Segoe UI", 11, "bold"))
    style.map("Accent.TButton", background=[("active", OK_GREEN)])
    style.configure("TSpinbox",   fieldbackground=ENTRY_BG, foreground=FG, insertcolor=FG)
    style.configure("Header.TLabel", font=("Segoe UI", 14, "bold"), foreground=ACCENT)
    style.configure("Status.TLabel", font=("Segoe UI", 9), foreground=WARN_YEL)

    # ── Scroll container ─────────────────────────────────────────────────
    canvas = tk.Canvas(root_win, bg=BG, highlightthickness=0)
    scrollbar = ttk.Scrollbar(root_win, orient="vertical", command=canvas.yview)
    scroll_frame = ttk.Frame(canvas)

    scroll_frame.bind("<Configure>",
                      lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
    canvas.create_window((0, 0), window=scroll_frame, anchor="nw")
    canvas.configure(yscrollcommand=scrollbar.set)

    def _on_mousewheel(event):
        canvas.yview_scroll(int(-1 * (event.delta / 120 or -event.num + 4)), "units")

    canvas.bind_all("<MouseWheel>", _on_mousewheel)      # Windows / macOS
    canvas.bind_all("<Button-4>",   _on_mousewheel)       # Linux scroll up
    canvas.bind_all("<Button-5>",   _on_mousewheel)       # Linux scroll down

    scrollbar.pack(side="right", fill="y")
    canvas.pack(side="left", fill="both", expand=True)

    # Helpers
    PAD = {"padx": 8, "pady": 3}

    def _make_path_row(parent, label: str, var: tk.StringVar,
                       browse_type: str = "dir", filetypes=None) -> ttk.Frame:
        """Create a  [Label]  [────Entry────]  [Browse]  row."""
        fr = ttk.Frame(parent)
        ttk.Label(fr, text=label, width=18, anchor="e").pack(side="left", **PAD)
        ent = ttk.Entry(fr, textvariable=var, width=52)
        ent.pack(side="left", **PAD, fill="x", expand=True)

        def _browse():
            initial = var.get() or "/"
            if browse_type == "dir":
                chosen = filedialog.askdirectory(
                    title=f"Select {label}", initialdir=initial)
            else:
                chosen = filedialog.askopenfilename(
                    title=f"Select {label}", initialdir=str(Path(initial).parent),
                    filetypes=filetypes or [("All files", "*.*")])
            if chosen:
                var.set(chosen)

        ttk.Button(fr, text="Browse…", command=_browse).pack(side="left", **PAD)
        return fr

    def _make_status_label(parent) -> ttk.Label:
        lbl = ttk.Label(parent, text="", style="Status.TLabel")
        lbl.pack(anchor="w", padx=26, pady=(0, 2))
        return lbl

    # ─── Title ────────────────────────────────────────────────────────────
    ttk.Label(scroll_frame, text="🐦  AvisTrack — Config Wizard",
              style="Header.TLabel").pack(pady=(14, 4))
    ttk.Label(scroll_frame,
              text="Fill in the fields below.  Use Browse buttons to pick folders / files.",
              foreground="#a6adc8").pack(pady=(0, 10))

    # ═══ 1. Experiment ════════════════════════════════════════════════════
    sec1 = ttk.LabelFrame(scroll_frame, text="  1 ─ Experiment  ")
    sec1.pack(fill="x", padx=12, pady=6)

    var_name = tk.StringVar(value=prefill_name or "")
    fr = ttk.Frame(sec1)
    ttk.Label(fr, text="Experiment name", width=18, anchor="e").pack(side="left", **PAD)
    ttk.Entry(fr, textvariable=var_name, width=40).pack(side="left", **PAD)
    ttk.Label(fr, text='e.g. Wave2_Collective',
              foreground="#6c7086").pack(side="left", padx=4)
    fr.pack(fill="x", **PAD)

    # ═══ 2. Experiment root ══════════════════════════════════════════════
    sec2 = ttk.LabelFrame(scroll_frame, text="  2 ─ Experiment Root  ")
    sec2.pack(fill="x", padx=12, pady=6)
    ttk.Label(sec2, text="Top-level folder for this experiment (e.g. /media/.../Wave2), NOT the drive mount point.",
              foreground="#6c7086").pack(anchor="w", padx=26, pady=(2, 0))

    var_root = tk.StringVar(value=prefill_root or "/media/woodlab/")
    _make_path_row(sec2, "Experiment root", var_root, browse_type="dir").pack(fill="x", **PAD)
    status_root = _make_status_label(sec2)

    # ═══ 3. Drive paths ══════════════════════════════════════════════════
    sec3 = ttk.LabelFrame(scroll_frame, text="  3 ─ Drive Paths  ")
    sec3.pack(fill="x", padx=12, pady=6)

    ttk.Label(sec3, text="Click 'Auto-detect' after setting the experiment root, or browse manually.",
              foreground="#6c7086").pack(anchor="w", padx=26, pady=(2, 4))

    var_raw     = tk.StringVar()
    var_dataset = tk.StringVar()
    var_meta    = tk.StringVar()
    var_roi     = tk.StringVar()
    var_train_m = tk.StringVar()
    var_val_m   = tk.StringVar()
    var_test_m  = tk.StringVar()

    _make_path_row(sec3, "raw_videos",      var_raw,     "dir").pack(fill="x", **PAD)
    _make_path_row(sec3, "dataset (clips)",  var_dataset, "dir").pack(fill="x", **PAD)
    _make_path_row(sec3, "metadata",         var_meta,    "dir").pack(fill="x", **PAD)
    _make_path_row(sec3, "ROI file (.json)", var_roi,     "file",
                   filetypes=[("JSON", "*.json"), ("All", "*.*")]).pack(fill="x", **PAD)

    var_exclusions = tk.StringVar()
    var_ocr_roi    = tk.StringVar()
    var_time_cal   = tk.StringVar()
    _make_path_row(sec3, "exclusions (.json)", var_exclusions, "file",
                   filetypes=[("JSON", "*.json"), ("All", "*.*")]).pack(fill="x", **PAD)
    _make_path_row(sec3, "ocr_roi (.json)",    var_ocr_roi,   "file",
                   filetypes=[("JSON", "*.json"), ("All", "*.*")]).pack(fill="x", **PAD)
    _make_path_row(sec3, "time_calibration",   var_time_cal,  "file",
                   filetypes=[("JSON", "*.json"), ("All", "*.*")]).pack(fill="x", **PAD)

    _make_path_row(sec3, "train manifest",   var_train_m, "file",
                   filetypes=[("Text/CSV", "*.txt *.csv"), ("All", "*.*")]).pack(fill="x", **PAD)
    _make_path_row(sec3, "val manifest",     var_val_m,   "file",
                   filetypes=[("Text/CSV", "*.txt *.csv"), ("All", "*.*")]).pack(fill="x", **PAD)
    _make_path_row(sec3, "test manifest",    var_test_m,  "file",
                   filetypes=[("Text/CSV", "*.txt *.csv"), ("All", "*.*")]).pack(fill="x", **PAD)
    status_detect = _make_status_label(sec3)

    def _auto_detect():
        r = var_root.get().strip()
        if not r:
            status_root.config(text="⚠  Set drive root first.", foreground=WARN_YEL)
            return
        detected = _detect_structure(r)
        n_found = 0
        if "raw_videos" in detected:
            var_raw.set(detected["raw_videos"]); n_found += 1
        else:
            var_raw.set(f"{r}/00_raw_videos")
        if "dataset" in detected:
            var_dataset.set(detected["dataset"]); n_found += 1
        else:
            var_dataset.set(f"{r}/01_Dataset_MOT_Format")
        if "metadata" in detected:
            var_meta.set(detected["metadata"]); n_found += 1
        else:
            var_meta.set(f"{r}/02_Global_Metadata")

        meta = var_meta.get()
        roi = _find_roi_file(r)
        var_roi.set(roi or f"{meta}/camera_rois.json")
        var_exclusions.set(f"{meta}/exclusions.json")
        var_ocr_roi.set(f"{meta}/ocr_roi.json")
        var_time_cal.set(f"{meta}/time_calibration.json")
        var_train_m.set(f"{meta}/train_data_manifest.txt")
        var_val_m.set(f"{meta}/val_tuning_manifest.txt")
        var_test_m.set(f"{meta}/test_golden_manifest.txt")

        # weights
        wts = _find_weights(r)
        if wts:
            var_weights.set(wts[0])
            combo_weights["values"] = wts
            status_weights.config(text=f"✓ Found {len(wts)} weight file(s)", foreground=OK_GREEN)

        if n_found:
            status_detect.config(text=f"✓ Auto-detected {n_found} standard directories",
                                 foreground=OK_GREEN)
            status_root.config(text=f"✓ Root exists", foreground=OK_GREEN)
        elif Path(r).exists():
            status_detect.config(text="⚠ No standard dirs found; defaults applied",
                                 foreground=WARN_YEL)
            status_root.config(text=f"✓ Root exists", foreground=OK_GREEN)
        else:
            status_detect.config(text="⚠ Root not mounted; defaults applied",
                                 foreground=WARN_YEL)
            status_root.config(text="⚠ Root does not exist", foreground=WARN_YEL)

    ttk.Button(sec3, text="⟳  Auto-detect from root", command=_auto_detect).pack(
        anchor="w", padx=26, pady=6)

    # ═══ 4. Chamber ══════════════════════════════════════════════════════
    sec4 = ttk.LabelFrame(scroll_frame, text="  4 ─ Chamber Parameters  ")
    sec4.pack(fill="x", padx=12, pady=6)

    fr4 = ttk.Frame(sec4)
    fr4.pack(fill="x", **PAD)

    var_subjects = tk.IntVar(value=9)
    var_fps      = tk.IntVar(value=30)
    var_tw       = tk.IntVar(value=640)
    var_th       = tk.IntVar(value=640)

    for label, var, lo, hi in [
        ("Subjects",           var_subjects, 1, 100),
        ("FPS",                var_fps,      1, 240),
        ("Inference width",    var_tw,       64, 4096),
        ("Inference height",   var_th,       64, 4096),
    ]:
        sub = ttk.Frame(fr4)
        ttk.Label(sub, text=label, width=16, anchor="e").pack(side="left", **PAD)
        ttk.Spinbox(sub, textvariable=var, from_=lo, to=hi, width=8).pack(side="left", **PAD)
        sub.pack(fill="x")

    # ═══ 5. Model ════════════════════════════════════════════════════════
    sec5 = ttk.LabelFrame(scroll_frame, text="  5 ─ Model  ")
    sec5.pack(fill="x", padx=12, pady=6)

    fr5a = ttk.Frame(sec5)
    fr5a.pack(fill="x", **PAD)

    var_backend = tk.StringVar(value="yolo")
    var_mode    = tk.StringVar(value="offline")

    sub = ttk.Frame(fr5a)
    ttk.Label(sub, text="Backend", width=18, anchor="e").pack(side="left", **PAD)
    ttk.Combobox(sub, textvariable=var_backend, values=["yolo", "dlc", "vit"],
                 state="readonly", width=14).pack(side="left", **PAD)
    ttk.Label(sub, text="Mode", width=6, anchor="e").pack(side="left", **PAD)
    ttk.Combobox(sub, textvariable=var_mode, values=["offline", "realtime"],
                 state="readonly", width=14).pack(side="left", **PAD)
    sub.pack(fill="x")

    # Weights: combo (auto-found) + browse button
    var_weights = tk.StringVar()
    fr5w = ttk.Frame(sec5)
    ttk.Label(fr5w, text="Weights", width=18, anchor="e").pack(side="left", **PAD)
    combo_weights = ttk.Combobox(fr5w, textvariable=var_weights, width=48)
    combo_weights.pack(side="left", **PAD, fill="x", expand=True)

    def _browse_weights():
        chosen = filedialog.askopenfilename(
            title="Select weight file",
            filetypes=[("PyTorch", "*.pt"), ("HDF5", "*.h5"), ("All", "*.*")])
        if chosen:
            var_weights.set(chosen)

    ttk.Button(fr5w, text="Browse…", command=_browse_weights).pack(side="left", **PAD)
    fr5w.pack(fill="x", **PAD)
    status_weights = _make_status_label(sec5)

    # ═══ 6. Tracking & Pipeline ══════════════════════════════════════════
    sec6 = ttk.LabelFrame(scroll_frame, text="  6 ─ Tracking & Pipeline  ")
    sec6.pack(fill="x", padx=12, pady=6)

    var_conf = tk.DoubleVar(value=0.2)
    var_gap  = tk.IntVar(value=30)
    var_transform = tk.BooleanVar(value=True)

    fr6 = ttk.Frame(sec6)
    for label, var, lo, hi in [
        ("Conf threshold",   var_conf, 0.0, 1.0),
        ("Max gap frames",   var_gap,  0,   300),
    ]:
        sub = ttk.Frame(fr6)
        ttk.Label(sub, text=label, width=18, anchor="e").pack(side="left", **PAD)
        ttk.Spinbox(sub, textvariable=var, from_=lo, to=hi, width=8,
                    increment=0.05 if isinstance(var, tk.DoubleVar) else 1).pack(
            side="left", **PAD)
        sub.pack(fill="x")
    fr6.pack(fill="x", **PAD)

    ttk.Checkbutton(sec6, text="Include perspective transform step",
                    variable=var_transform).pack(anchor="w", padx=26, pady=4)

    # ═══ 7. Output ═══════════════════════════════════════════════════════
    sec7 = ttk.LabelFrame(scroll_frame, text="  7 ─ Output  ")
    sec7.pack(fill="x", padx=12, pady=6)

    var_fmt = tk.StringVar(value="mot")
    sub = ttk.Frame(sec7)
    ttk.Label(sub, text="Format", width=18, anchor="e").pack(side="left", **PAD)
    ttk.Combobox(sub, textvariable=var_fmt, values=["mot", "parquet"],
                 state="readonly", width=14).pack(side="left", **PAD)
    sub.pack(fill="x", **PAD)

    var_outdir = tk.StringVar(value="./outputs")
    _make_path_row(sec7, "Output directory", var_outdir, "dir").pack(fill="x", **PAD)

    # ═══ 8. Time Calibration ═════════════════════════════════════════════
    sec8 = ttk.LabelFrame(scroll_frame, text="  8 ─ Time Calibration  ")
    sec8.pack(fill="x", padx=12, pady=6)
    ttk.Label(sec8,
              text="Used by tools/calibrate_time.py to map video frames to wall-clock time via OCR.",
              foreground="#6c7086").pack(anchor="w", padx=26, pady=(2, 4))

    var_tz   = tk.StringVar(value="America/New_York")
    var_tfmt = tk.StringVar(value="%I:%M:%S %p")

    fr8 = ttk.Frame(sec8)
    sub = ttk.Frame(fr8)
    ttk.Label(sub, text="Timezone (IANA)", width=18, anchor="e").pack(side="left", **PAD)
    ttk.Entry(sub, textvariable=var_tz, width=30).pack(side="left", **PAD)
    ttk.Label(sub, text="e.g. America/New_York", foreground="#6c7086").pack(side="left", padx=4)
    sub.pack(fill="x")

    sub2 = ttk.Frame(fr8)
    ttk.Label(sub2, text="Time format", width=18, anchor="e").pack(side="left", **PAD)
    ttk.Entry(sub2, textvariable=var_tfmt, width=30).pack(side="left", **PAD)
    ttk.Label(sub2, text="strptime format for burn-in text", foreground="#6c7086").pack(side="left", padx=4)
    sub2.pack(fill="x")
    fr8.pack(fill="x", **PAD)

    # ═══ Status bar ══════════════════════════════════════════════════════
    status_bar = ttk.Label(scroll_frame, text="", style="Status.TLabel")
    status_bar.pack(fill="x", padx=16, pady=(8, 2))

    # ═══ Generate button ═════════════════════════════════════════════════
    def _on_generate():
        name = var_name.get().strip()
        if not name:
            messagebox.showwarning("Missing field", "Experiment name is required.")
            return
        r = var_root.get().strip()
        if not r:
            messagebox.showwarning("Missing field", "Drive root is required.")
            return
        w = var_weights.get().strip()

        pipeline = []
        if var_transform.get():
            pipeline.append("transform")
        pipeline.append("track")

        cfg = {
            "experiment":      name,
            "root":            r,
            "raw_videos":      var_raw.get()     or f"{r}/00_raw_videos",
            "dataset":         var_dataset.get() or f"{r}/01_Dataset_MOT_Format",
            "metadata":        var_meta.get()    or f"{r}/02_Global_Metadata",
            "roi_file":        var_roi.get()     or f"{r}/02_Global_Metadata/camera_rois.json",
            "exclusions":      var_exclusions.get() or f"{r}/02_Global_Metadata/exclusions.json",
            "ocr_roi":         var_ocr_roi.get()    or f"{r}/02_Global_Metadata/ocr_roi.json",
            "time_calibration": var_time_cal.get()   or f"{r}/02_Global_Metadata/time_calibration.json",
            "train_manifest":  var_train_m.get() or f"{r}/02_Global_Metadata/train_data_manifest.txt",
            "val_manifest":    var_val_m.get()   or f"{r}/02_Global_Metadata/val_tuning_manifest.txt",
            "test_manifest":   var_test_m.get()  or f"{r}/02_Global_Metadata/test_golden_manifest.txt",
            "n_subjects":      var_subjects.get(),
            "fps":             var_fps.get(),
            "target_w":        var_tw.get(),
            "target_h":        var_th.get(),
            "backend":         var_backend.get(),
            "model_mode":      var_mode.get(),
            "weights":         w or "",
            "conf_threshold":  var_conf.get(),
            "max_gap_frames":  var_gap.get(),
            "pipeline":        pipeline,
            "output_format":   var_fmt.get(),
            "output_dir":      var_outdir.get() or f"{r}/../outputs/{name}",
            "timezone":        var_tz.get()  or "America/New_York",
            "time_format":     var_tfmt.get() or "%I:%M:%S %p",
        }

        warnings = _validate_config(cfg)
        yaml_content = _generate_yaml(cfg)

        # Ask where to save
        safe = re.sub(r"[^A-Za-z0-9_\-]", "_", name).lower()
        default_name = f"{safe}.yaml"
        script_dir = Path(__file__).parent.parent / "configs"
        out = filedialog.asksaveasfilename(
            title="Save config YAML",
            initialdir=str(script_dir),
            initialfile=default_name,
            defaultextension=".yaml",
            filetypes=[("YAML", "*.yaml *.yml"), ("All", "*.*")],
        )
        if not out:
            return

        out_path = Path(out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(yaml_content)

        # Show result
        warn_text = ""
        if warnings:
            warn_text = "\n\nWarnings:\n• " + "\n• ".join(warnings)
        messagebox.showinfo(
            "Config saved",
            f"✓ Written to:\n{out_path}\n{warn_text}\n\n"
            f"Next steps:\n"
            f"1. python tools/pick_rois.py ...\n"
            f"2. python tools/sample_clips.py --config {out_path} ...\n"
            f"3. python cli/run_batch.py --config {out_path}"
        )
        status_bar.config(text=f"✓ Saved → {out_path}", foreground=OK_GREEN)

    btn_frame = ttk.Frame(scroll_frame)
    btn_frame.pack(pady=14)
    ttk.Button(btn_frame, text="  💾  Generate Config  ",
               style="Accent.TButton", command=_on_generate).pack()

    # ── Auto-detect on launch if root was pre-filled ─────────────────────
    if prefill_root:
        root_win.after(200, _auto_detect)

    root_win.mainloop()


# ══════════════════════════════════════════════════════════════════════════
#  CLI fallback  (--cli flag)
# ══════════════════════════════════════════════════════════════════════════

BLUE   = "\033[94m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
RED    = "\033[91m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
RESET  = "\033[0m"


def _cli_ask(prompt, default=None, required=True):
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            raw = input(f"  {prompt}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n\nAborted."); sys.exit(0)
        value = raw or default
        if value or not required:
            return value or ""
        print(f"  {RED}→ Required.{RESET}")


def _cli_ask_int(prompt, default=None):
    while True:
        raw = _cli_ask(prompt, str(default) if default else None)
        try: return int(raw)
        except ValueError: print(f"  {RED}→ Enter a number.{RESET}")


def _cli_ask_float(prompt, default=None):
    while True:
        raw = _cli_ask(prompt, str(default) if default else None)
        try: return float(raw)
        except ValueError: print(f"  {RED}→ Enter a number.{RESET}")


def _cli_ask_choice(prompt, options, default=None):
    for i, o in enumerate(options, 1):
        m = " (default)" if o == default else ""
        print(f"    {BOLD}{i}{RESET}. {o}{m}")
    while True:
        raw = _cli_ask(prompt, default, required=True)
        if raw in options: return raw
        try:
            idx = int(raw) - 1
            if 0 <= idx < len(options): return options[idx]
        except ValueError: pass
        print(f"  {RED}→ Choose 1-{len(options)}.{RESET}")


def _cli_ask_yes_no(prompt, default=True):
    raw = _cli_ask(f"{prompt} ({'Y/n' if default else 'y/N'})", required=False)
    if not raw: return default
    return raw.lower().startswith("y")


def _cli_ask_path(prompt, default=None, must_exist=False, check_warning=True):
    while True:
        raw = _cli_ask(prompt, default)
        expanded = os.path.expanduser(raw)
        if must_exist and not Path(expanded).exists():
            print(f"  {RED}✗ Does not exist: {expanded}{RESET}"); continue
        if check_warning and not must_exist and not Path(expanded).exists():
            print(f"  {YELLOW}⚠ Does not exist yet: {expanded}{RESET}")
            if not _cli_ask_yes_no("Use it anyway?", True): continue
        return expanded


def _run_cli(prefill_root=None, prefill_name=None, output_path=None):
    print(f"\n{BOLD}╔════════════════════════════════════════════╗")
    print(f"║     AvisTrack — Config Wizard  (CLI)       ║")
    print(f"╚════════════════════════════════════════════╝{RESET}\n")

    cfg = {}

    print(f"{BOLD}{BLUE}── 1/8  Experiment Name ──{RESET}")
    cfg["experiment"] = _cli_ask("Experiment name", default=prefill_name)

    print(f"\n{BOLD}{BLUE}── 2/8  Experiment Root ──{RESET}")
    print("  (Top-level folder for this experiment, e.g. /media/.../Wave2)")
    cfg["root"] = _cli_ask_path("Experiment root path", default=prefill_root, must_exist=False)
    root = cfg["root"]
    detected = _detect_structure(root)
    if detected:
        print(f"  {GREEN}✓ Found: {', '.join(detected.keys())}{RESET}")

    print(f"\n{BOLD}{BLUE}── 3/8  Drive Paths ──{RESET}")
    def _dod(key, fallback): return detected.get(key, f"{root}/{fallback}")
    cfg["raw_videos"]     = _cli_ask_path("raw_videos dir",   _dod("raw_videos", "00_raw_videos"),      check_warning=Path(root).exists())
    cfg["dataset"]        = _cli_ask_path("dataset dir",      _dod("dataset",    "01_Dataset_MOT_Format"), check_warning=False)
    cfg["metadata"]       = _cli_ask_path("metadata dir",     _dod("metadata",   "02_Global_Metadata"),    check_warning=False)
    roi = _find_roi_file(root)
    cfg["roi_file"]       = _cli_ask_path("ROI file",         roi or f"{cfg['metadata']}/camera_rois.json", check_warning=False)
    meta = cfg["metadata"]
    cfg["exclusions"]      = _cli_ask_path("exclusions.json",   f"{meta}/exclusions.json",         check_warning=False)
    cfg["ocr_roi"]         = _cli_ask_path("ocr_roi.json",     f"{meta}/ocr_roi.json",            check_warning=False)
    cfg["time_calibration"] = _cli_ask_path("time_calibration", f"{meta}/time_calibration.json",   check_warning=False)
    cfg["train_manifest"] = _cli_ask_path("train manifest",   f"{meta}/train_data_manifest.txt",  check_warning=False)
    cfg["val_manifest"]   = _cli_ask_path("val manifest",     f"{meta}/val_tuning_manifest.txt",  check_warning=False)
    cfg["test_manifest"]  = _cli_ask_path("test manifest",    f"{meta}/test_golden_manifest.txt", check_warning=False)

    print(f"\n{BOLD}{BLUE}── 4/8  Chamber ──{RESET}")
    cfg["n_subjects"] = _cli_ask_int("Number of subjects", 9)
    cfg["fps"]        = _cli_ask_int("Video FPS", 30)
    cfg["target_w"]   = _cli_ask_int("Inference width", 640)
    cfg["target_h"]   = _cli_ask_int("Inference height", 640)

    print(f"\n{BOLD}{BLUE}── 5/8  Model ──{RESET}")
    cfg["backend"]    = _cli_ask_choice("Backend", ["yolo", "dlc", "vit"], "yolo")
    cfg["model_mode"] = _cli_ask_choice("Mode", ["offline", "realtime"], "offline") \
                        if cfg["backend"] == "yolo" else "offline"
    wts = _find_weights(root)
    if wts:
        print(f"  {GREEN}✓ Found {len(wts)} .pt file(s):{RESET}")
        for i, w in enumerate(wts, 1):
            print(f"    {BOLD}{i}{RESET}. {w.replace(root, '{root}')}")
        ch = _cli_ask(f"Pick 1-{len(wts)}, enter path, or press Enter to skip", required=False)
        if not ch:
            cfg["weights"] = ""
            print(f"  {YELLOW}⚠ Weights skipped (not yet trained){RESET}")
        else:
            try:
                idx = int(ch) - 1
                cfg["weights"] = wts[idx] if 0 <= idx < len(wts) else ch
            except ValueError:
                cfg["weights"] = os.path.expanduser(ch)
    else:
        print(f"  {YELLOW}No .pt files found under {root}/03_Model_Training{RESET}")
        ch = _cli_ask("Weights path (or press Enter to skip)", required=False)
        cfg["weights"] = os.path.expanduser(ch) if ch else ""

    print(f"\n{BOLD}{BLUE}── 6/8  Tracking & Pipeline ──{RESET}")
    cfg["conf_threshold"] = _cli_ask_float("Confidence threshold", 0.2)
    cfg["max_gap_frames"] = _cli_ask_int("Max gap frames", 30)
    cfg["pipeline"] = (["transform"] if _cli_ask_yes_no("Include perspective transform?", True) else []) + ["track"]

    print(f"\n{BOLD}{BLUE}── 7/8  Output ──{RESET}")
    cfg["output_format"] = _cli_ask_choice("Format", ["mot", "parquet"], "mot")
    cfg["output_dir"]    = _cli_ask_path("Output directory", f"{root}/../outputs/{cfg['experiment']}", check_warning=False)

    print(f"\n{BOLD}{BLUE}── 8/8  Time Calibration ──{RESET}")
    print("  (Used by tools/calibrate_time.py to map frame↔burn-in time via OCR)")
    cfg["timezone"]    = _cli_ask("Timezone (IANA)", "America/New_York")
    cfg["time_format"] = _cli_ask("Time format (strptime)", "%I:%M:%S %p")

    # Summary
    print(f"\n{BOLD}{'─'*50}{RESET}")
    for k, v in [("Experiment", cfg["experiment"]), ("Root", cfg["root"]),
                 ("Backend", f"{cfg['backend']} ({cfg['model_mode']})"),
                 ("Weights", cfg["weights"] or "(none — not yet trained)"), ("Pipeline", " → ".join(cfg["pipeline"]))]:
        print(f"  {k:14s}  {v}")

    for w in _validate_config(cfg):
        print(f"  {YELLOW}⚠ {w}{RESET}")

    safe = re.sub(r"[^A-Za-z0-9_\-]", "_", cfg["experiment"]).lower()
    out = Path(_cli_ask("Save config to", output_path or f"configs/{safe}.yaml"))
    if out.exists() and not _cli_ask_yes_no(f"{out} exists. Overwrite?", False):
        print("Aborted."); sys.exit(0)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_generate_yaml(cfg))
    print(f"  {GREEN}✓ Config written to {out}{RESET}")
    print(f"\n{BOLD}Next steps:{RESET}")
    print(f"  python tools/sample_clips.py --config {out} --split train --n 20 --duration 3 ...")
    print(f"  python cli/run_batch.py --config {out}\n")


# ══════════════════════════════════════════════════════════════════════════
#  Entry point
# ══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="AvisTrack config wizard (GUI by default, --cli for terminal).",
    )
    parser.add_argument("--cli", action="store_true", help="Use terminal mode instead of GUI")
    parser.add_argument("--root", help="Pre-fill drive root path")
    parser.add_argument("--name", help="Pre-fill experiment name")
    parser.add_argument("--output", "-o", help="Output YAML path (CLI mode only)")
    args = parser.parse_args()

    if args.cli:
        _run_cli(prefill_root=args.root, prefill_name=args.name, output_path=args.output)
    else:
        try:
            import tkinter  # noqa: F401
        except ImportError:
            print("tkinter not available — falling back to CLI mode.\n"
                  "  (Install: sudo apt install python3-tk)\n")
            _run_cli(prefill_root=args.root, prefill_name=args.name, output_path=args.output)
            return
        _run_gui(prefill_root=args.root, prefill_name=args.name)


if __name__ == "__main__":
    main()
